#!/sbin/sh

. "$env"

print "Removing ZRAM in the fstab ..."

found_fstab=false

for fstab in fstab.*; do
	[ -f "$fstab" ] || continue
	print "Found fstab: $fstab"
	sed -i "
		/zram/d
	" "$fstab"
	found_fstab=true
done

$found_fstab || print "Unable to find the fstab!"

exit 0
